### PR TITLE
Here is my code for Homework 2

### PR DESCRIPTION
**Pull request by JeremiahTilse**

### CODE REVIEW

**Comment by schoure98** [comment]
coin.js -> I recently discovered Math.trunc() and prefer to use it over Math.floor(), please see if you find it useful. I appreciate the test cases you have considered like if nan or a negative number is received. Is there any specific reason you have converted the input into string? 

reverse-> If the number received is negative, it is still returning the error, enter 8 digit number. I am facing the same issue, let me know if you find how to include negative numbers as well. I tried implementing Math.sign() not working out for me. 

form-> the code looks good, easy to understand and working out well. 

api-> Looks good.

**Comment by mattadlerpdx** [comment]
- 01-coins: excellent job making sure the input is correct. Negative value, making sure it isn’t too big, and making sure it is a proper dollar amount. Comments are excellent as well. Easy to follow logic. That said also, I really like how you went about designing the program. No use of many functions either.  This is good. Somehthing I should have done. I find functions overuse hard to read. Use of let and const is perfect. No real critiques. 
- 02-reverse: excellently commented. Also good use of let (variable limited to scope). 
- 03-form: perfect use of console warning i.e use of console.groupStart()
- 04-api: perfect use of const and lets. Perhaps naming convention for array ‘data’ could be more precise. Perhaps countries? Line 37

**Comment by JeremiahTilse** [comment]
> coin.js -> I recently discovered Math.trunc() and prefer to use it over Math.floor(), please see if you find it useful. I appreciate the test cases you have considered like if nan or a negative number is received. Is there any specific reason you have converted the input into string?

I was unaware of Math.trunc().  It would be a much more appropriate to use, especially if negatives were allowed.  I did miss a couple test cases, null and empty string.  A lot of the converting to string came from using a different method of formatting the output, and I didn't think to change it when I switched.  When checking isNaN, I did it out of a habit that I'm not sure where I picked up, or why, and for checking if proper dollar amount, it was just easier to check the length of the string since nothing longer that four characters could be accepted anyway.

> 
> reverse-> If the number received is negative, it is still returning the error, enter 8 digit number. I am facing the same issue, let me know if you find how to include negative numbers as well. I tried implementing Math.sign() not working out for me.

I hadn't considered negative numbers, or even decimals...  I didn't bother doing a check to see if the input was a number or not, since the field was already filtering for that.  I think it might be possible to check if negative, a decimal, or both, before converting to string and checking length (8 if neither, 9 if either, and 10 if both).

Thanks for the feedback.  Definitely, some things to consider/change.

**Comment by JeremiahTilse** [comment]
> * 04-api: perfect use of const and lets. Perhaps naming convention for array ‘data’ could be more precise. Perhaps countries? Line 37

I think I was trying to remain abstract.  The data coming in was an object with the country name as the key and the population as the value.  I put the keys into an array so I could sort them, and then used the sorted array to pull the populations out in the order I wanted.  There might be a better way to do it, but I couldn't find it. 

I could just as easily named the function "addData" instead of "addCountries."  

Thanks for the input.

**Pull request merged**
