### PR TITLE
Checkout my FizzBuzz for Hw1

### PR DESCRIPTION
**Pull request by JeremiahTilse**
Completed FizzBuzz function, and made some small changes based on reading of AirBnB style guidelines.  Also, made some changes to my Prettier settings to revert preferences used by my Capstone team.  

Interested in feedback, particularly on the first 'if' condition.   I added some additional parens for clarity after reading the AirBnB style guidelines, but Prettier removed them on save.

### CODE REVIEW

**Review by mattadlerpdx — CHANGES_REQUESTED** [review]
Wow this looks great Jeremiah. Particularly the logic of if/else if is easy to read and makes sense. Your use of 'let' is ideal since the variable 'i' is block scoped. Great use of strict equality.
- Perhaps add a single line comment by replacing 'add your code here' with what you are declaring.

**Comment by C3ra906** [comment]
Hi Jeremiah, 

I love how clean your code is! I actually don't have any suggestions to make because your if/else statements are so clean and easy to understand. I liked that you followed the Airbnb JS Style Guide and used i += 1 instead of i++. I totally forgot about that in my own code. Great job!

**Comment by schoure98** [comment]
I think the JS code looks good. Its simple and and easy to be reviewed by others.

**Comment by Alvin-PDX** [comment]
It's about as concise as it can be line-wise and easy to understand. I think you did a great job.

**Pull request merged**
